# Generated by Django 5.2.8 on 2025-11-11 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('dob', models.DateField(blank=True)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text="Customer's face photo", null=True, upload_to='customers/photos/')),
                ('id_proof', models.ImageField(blank=True, help_text="Photo of customer's ID proof (e.g., passport, license)", upload_to='customers/id_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(default=dict)),
            ],
        ),
    ]
