# Generated by Django 5.2.8 on 2025-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_proof_document_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(),
        ),
    ]
