# Generated by Django 5.2.8 on 2025-11-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_customer_id_proof_document_number_alter_customer_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='preferences',
        ),
    ]
