# Generated by Django 5.2.8 on 2025-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_rename_photo_customer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.ImageField(help_text="Photo of customer's ID proof (e.g., passport, license)", upload_to='customers/id_proofs/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(help_text="Customer's face photo", upload_to='customers/photos/'),
        ),
    ]
