# Generated by Django 5.2.8 on 2025-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_alter_customer_country_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.CharField(help_text='Enter in DD-MM-YYYY format', max_length=10),
        ),
    ]
