# Generated by Django 5.2.8 on 2025-11-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0002_amenity_remove_roomtype_amenities_roomtype_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('reserved', 'reserved'), ('maintenance', 'maintenance')], max_length=20),
        ),
    ]
