# Generated by Django 5.2.8 on 2025-11-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0003_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per person', max_digits=10),
        ),
    ]
