# Generated by Django 5.2.8 on 2026-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0006_alter_room_id_alter_roomtype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='ac_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AC Rate per person', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, help_text='Non-AC Rate per person', max_digits=10),
        ),
    ]
