# Generated by Django 5.2.8 on 2026-07-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_service', '0007_roomtype_ac_rate_alter_roomtype_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='ac_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AC Rate', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, help_text='Non-AC Rate', max_digits=10),
        ),
    ]
