version: "3.9"

services:
  web:
    container_name: hotelbooking_web
    build: .
    env_file:
      - .env
    environment:
      # Point DB_HOST to the external MySQL container's name
      DB_HOST: mysql
    ports:
      - "8000:8000"
    networks:
      - shared-network
    restart: always

networks:
  shared-network:
    external: true
