# Generated by Django 5.2.8 on 2025-11-12 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('meal', 'meal'), ('travel', 'travel'), ('other', 'other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='per_item', max_length=20)),
                ('attributes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(null=True)),
                ('customer_id', models.UUIDField()),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
