# Generated by Django 5.2.8 on 2025-11-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_service', '0001_initial'),
        ('booking_service', '0006_alter_booking_room'),
        ('customer_service', '0004_alter_customer_id_proof_alter_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='items',
            new_name='items_list',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='booking_service.booking'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='customer_service.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='additional_service.serviceorder')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='additional_service.serviceitem')),
            ],
        ),
    ]
