# Generated by Django 5.2.8 on 2025-11-12 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_service', '0002_rename_items_serviceorder_items_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='items_list',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_type',
            field=models.CharField(choices=[('meal', 'Meal'), ('travel', 'Travel'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
