# Generated by Django 5.2.8 on 2025-11-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_service', '0003_remove_serviceorder_items_list_and_more'),
        ('booking_service', '0011_remove_booking_unique_room_booking_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='booking',
            field=models.ForeignKey(blank=True, limit_choices_to={'booking_status': 'checkin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='booking_service.booking'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='ordered', max_length=20),
        ),
    ]
