# Generated by Django 5.2.8 on 2025-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_service', '0004_alter_serviceorder_booking_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
