# Generated by Django 5.2.8 on 2026-03-20 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_service', '0005_serviceorderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
