# Generated by Django 5.2.8 on 2025-11-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_contacts_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
