# Generated by Django 5.2.8 on 2025-11-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0006_alter_booking_room'),
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbill',
            name='booking',
            field=models.OneToOneField(limit_choices_to={'status': 'reserved'}, on_delete=django.db.models.deletion.CASCADE, related_name='final_bill', to='booking_service.booking'),
        ),
    ]
