# Generated by Django 5.2.8 on 2025-11-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0011_remove_booking_unique_room_booking_dates'),
        ('payment_service', '0002_alter_finalbill_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbill',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_bill', to='booking_service.booking'),
        ),
    ]
