# Generated by Django 5.2.8 on 2026-03-20 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0003_alter_finalbill_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalbill',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
