# Generated by Django 5.2.8 on 2026-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0004_alter_finalbill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalbill',
            name='additional_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
