# Generated by Django 5.2.8 on 2025-11-12 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0001_initial'),
        ('room_service', '0003_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(limit_choices_to={'status': 'available'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='room_service.room'),
        ),
    ]
