# Generated by Django 5.2.8 on 2025-11-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0002_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_days',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
