# Generated by Django 5.2.8 on 2025-11-12 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0003_booking_num_days'),
        ('room_service', '0004_alter_roomtype_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='room_service.room'),
        ),
    ]
