# Generated by Django 5.2.8 on 2025-11-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0004_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
