# Generated by Django 5.2.8 on 2025-11-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0006_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
