# Generated by Django 5.2.8 on 2025-11-13 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0008_alter_booking_room_alter_booking_total_amount'),
        ('room_service', '0005_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(limit_choices_to={'status': 'available'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='room_service.room'),
        ),
    ]
