# Generated by Django 5.2.8 on 2025-11-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0009_booking_booking_status_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('occupied', 'Occupied'), ('checkin', 'checkin'), ('checkout', 'checkout'), ('cancelled', 'cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
