# Generated by Django 5.2.8 on 2025-11-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0010_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_room_booking_dates',
        ),
    ]
