# Generated by Django 5.2.8 on 2026-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0012_contactmessage_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_ac',
            field=models.BooleanField(default=False, help_text='Did the customer opt for AC?'),
        ),
    ]
