# Generated by Django 5.2.8 on 2026-08-24 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0013_booking_is_ac'),
        ('room_service', '0008_alter_roomtype_ac_rate_alter_roomtype_base_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='room_service.room'),
        ),
        migrations.CreateModel(
            name='BookingSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ac', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='booking_service.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_segments', to='room_service.room')),
            ],
            options={
                'verbose_name': 'Booking Segment',
                'verbose_name_plural': 'Booking Segments',
                'ordering': ['start_date', 'created_at'],
            },
        ),
    ]
