# Generated by Django 5.2.8 on 2025-11-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('room', 'Room'), ('food', 'Food'), ('service', 'Extra Service'), ('misc', 'Miscellaneous')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
